### PR TITLE
Dump to .model file

### LINKED ISSUE #7: .model file type
Create and define our own file type that can store an entire network. This allows us to temporarily store and restore training progress.

Possible implementation:
1. Json format
2. Toml format

Entries need to be determined later...

**UPD:**
The full network can be obtained by inspecting the genome (genotype). Therefore we need the following:
* Node genes
  * Node number (integer)
  * Node type (Enum: sensor, output, hidden)
* Connection genes
  * In node
  * Out node
  * Edge weight
  * Enable bit
  * Innovation number

### PR DESCRIPTION
**Pull request by XwanXuanX**
1. Define node and connection genes
2. Define genotype
3. Define .model file type and contents
4. Can dump genotype to .model file

### CODE REVIEW

**Comment by XwanXuanX** [comment]
After new fix it can be built and run on docker container as well.

**Comment by XwanXuanX** [comment]
After new fix it can be built and run on docker container as well.

**Comment by XwanXuanX** [comment]
@zicongleoqu 

IMPORTANT:
Please first finish the review of PR #16 before start reviewing this PR, since PR #16 is merging into this branch.

**Review by zicongleoqu — APPROVED** [review]
Approve

**Pull request merged**
